[package]
name = "gpa_calculator"
version = "0.1.0"
authors = ["Conrad Mo"]
license = "MIT"
edition = "2021"
rust-version = "1.64"
publish = false


[dependencies]
# eframe = { path = "../../crates/eframe" }
eframe = { version = "0.19.0", features = ["persistence"] }
